### ISSUE TITLE
Bad System Call

### ISSUE THREAD

**Issue by 7Ragnarok7** [MasterDevX/Termux-Java#23] opened 2020-06-12 08:00 UTC
Shows Bad system call after installing and trying to run java --version or java or javac

**Comment by DeicPro** [comment] 2020-06-12 16:48
Same

**Comment by maleko48** [comment] 2020-06-14 14:21
same here on LG V60 non-rooted stock phone w/Android 10

**Comment by sencrash** [comment] 2020-06-18 12:20
Duplicate of #3

**Comment by 7Ragnarok7** [comment] 2020-06-18 16:04
Hello @everyone This issue has already been solved.
You have to use proot -0 to get root permission and then call java or javac and it should work.

I'm closing this thread.

**Comment by 7Ragnarok7** [comment] 2020-06-18 16:05
> Hello @everyone This issue has already been solved.
> You have to use proot -0 to get root permission and then call java or javac and it should work.
> 
> I'm closing this thread.

**Comment by 7Ragnarok7** [comment] 2020-07-02 06:33
Hello @everyone This issue has already been solved.
You have to use proot -0 to get root permission and then call java or javac and it should work.

Please close this thread @MasterDevX
Thank You @sencrash .

**Closed** 2020-07-02 06:32 UTC
